export const EVENT_MANAGER_ABI = [
  // ─── Write functions ──────────────────────────────────────────────────────
  {
    type: 'function',
    name: 'createPublicEvent',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'eventName', type: 'string' },
      { name: 'startDate', type: 'uint256' },
      { name: 'endDate', type: 'uint256' },
      { name: 'entryToken', type: 'address' },
      { name: 'entryFee', type: 'uint256' },
      { name: 'scoringRule', type: 'uint8' },
    ],
    outputs: [{ name: 'eventId', type: 'uint256' }],
  },

  {
    type: 'function',
    name: 'joinEvent',
    stateMutability: 'payable',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [],
  },

  {
    type: 'function',
    name: 'addMatch',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'eventId', type: 'uint256' },
      { name: 'homeTeam', type: 'string' },
      { name: 'awayTeam', type: 'string' },
      { name: 'apiMatchId', type: 'string' },
      { name: 'kickoffTime', type: 'uint256' },
      { name: 'predictionDeadline', type: 'uint256' },
      { name: 'allowScorePrediction', type: 'bool' },
      { name: 'allowOutcomePrediction', type: 'bool' },
    ],
    outputs: [{ name: 'matchId', type: 'uint256' }],
  },

  // ─── Events ───────────────────────────────────────────────────────────────
  {
    type: 'event',
    name: 'PublicEventCreated',
    inputs: [
      { name: 'eventId', type: 'uint256', indexed: true },
      { name: 'eventName', type: 'string', indexed: false },
      { name: 'startDate', type: 'uint256', indexed: false },
      { name: 'endDate', type: 'uint256', indexed: false },
      { name: 'entryFee', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'PrivateEventCreated',
    inputs: [
      { name: 'eventId', type: 'uint256', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'eventName', type: 'string', indexed: false },
      { name: 'startDate', type: 'uint256', indexed: false },
      { name: 'endDate', type: 'uint256', indexed: false },
      { name: 'entryFee', type: 'uint256', indexed: false },
      { name: 'maxParticipants', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'MatchAdded',
    inputs: [
      { name: 'matchId', type: 'uint256', indexed: true },
      { name: 'eventId', type: 'uint256', indexed: true },
      { name: 'homeTeam', type: 'string', indexed: false },
      { name: 'awayTeam', type: 'string', indexed: false },
      { name: 'apiMatchId', type: 'string', indexed: false },
      { name: 'kickoffTime', type: 'uint256', indexed: false },
      { name: 'allowScorePrediction', type: 'bool', indexed: false },
      { name: 'allowOutcomePrediction', type: 'bool', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'UserJoinedEvent',
    inputs: [
      { name: 'eventId', type: 'uint256', indexed: true },
      { name: 'user', type: 'address', indexed: true },
      { name: 'timestamp', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'MatchResultVerified',
    inputs: [
      { name: 'matchId', type: 'uint256', indexed: true },
      { name: 'eventId', type: 'uint256', indexed: true },
      { name: 'homeScore', type: 'uint8', indexed: false },
      { name: 'awayScore', type: 'uint8', indexed: false },
      { name: 'proof', type: 'bytes32', indexed: false },
      { name: 'agent', type: 'address', indexed: true },
      { name: 'timestamp', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'EventResolved',
    inputs: [
      { name: 'eventId', type: 'uint256', indexed: true },
      { name: 'winners', type: 'address[5]', indexed: false },
    ],
  },

  // ─── Read functions ───────────────────────────────────────────────────────
  {
    type: 'function',
    name: 'getEvent',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'eventId', type: 'uint256' },
          { name: 'eventType', type: 'uint8' },
          { name: 'creator', type: 'address' },
          { name: 'eventName', type: 'string' },
          { name: 'startDate', type: 'uint256' },
          { name: 'endDate', type: 'uint256' },
          { name: 'entryToken', type: 'address' },
          { name: 'entryFee', type: 'uint256' },
          { name: 'prizePool', type: 'uint256' },
          { name: 'maxParticipants', type: 'uint256' },
          { name: 'status', type: 'uint8' },
          { name: 'scoringRule', type: 'uint8' },
          { name: 'inviteCodeHash', type: 'bytes32' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getMatch',
    stateMutability: 'view',
    inputs: [{ name: 'matchId', type: 'uint256' }],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'matchId', type: 'uint256' },
          { name: 'eventId', type: 'uint256' },
          { name: 'homeTeam', type: 'string' },
          { name: 'awayTeam', type: 'string' },
          { name: 'apiMatchId', type: 'string' },
          { name: 'kickoffTime', type: 'uint256' },
          { name: 'predictionDeadline', type: 'uint256' },
          { name: 'status', type: 'uint8' },
          { name: 'finalHomeScore', type: 'uint8' },
          { name: 'finalAwayScore', type: 'uint8' },
          { name: 'resultProof', type: 'bytes32' },
          { name: 'verifiedAt', type: 'uint256' },
          { name: 'allowScorePrediction', type: 'bool' },
          { name: 'allowOutcomePrediction', type: 'bool' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getEventMatches',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ type: 'uint256[]' }],
  },
  {
    type: 'function',
    name: 'getParticipants',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ type: 'address[]' }],
  },
  {
    type: 'function',
    name: 'getParticipantCount',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getPrediction',
    stateMutability: 'view',
    inputs: [
      { name: 'matchId', type: 'uint256' },
      { name: 'user', type: 'address' },
    ],
    outputs: [
      { name: 'homeScore', type: 'uint8' },
      { name: 'awayScore', type: 'uint8' },
      { name: 'hasScorePrediction', type: 'bool' },
      { name: 'outcome', type: 'uint8' },
      { name: 'hasOutcomePrediction', type: 'bool' },
      { name: 'submittedAt', type: 'uint256' },
      { name: 'scorePointsEarned', type: 'uint256' },
      { name: 'outcomePointsEarned', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'getWinners',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [{ type: 'address[5]' }],
  },
  {
    type: 'function',
    name: 'hasJoined',
    stateMutability: 'view',
    inputs: [
      { name: 'eventId', type: 'uint256' },
      { name: 'user', type: 'address' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'nextEventId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'nextMatchId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'claimable',
    stateMutability: 'view',
    inputs: [
      { name: 'eventId', type: 'uint256' },
      { name: 'user', type: 'address' },
    ],
    outputs: [{ type: 'uint256' }],
  },
] as const;
